### ISSUE TITLE
HTML规范中规则与示例不一致问题

### ISSUE THREAD

**Issue by hisaspirations** [woai3c/front-end-specification#6]
阅读您HTML规范时发现对缩进的规则与示例不一致，缩进规则规定用“2个空格”作为一个缩进层级，但示例中是用的4个空格，不知是我理解有偏差，还是文档确需修改。

如图：
![image](https://github.com/user-attachments/assets/d43cfbf6-285e-4344-9b46-0ce40d88ed80)

**Comment by woai3c** [comment]
> 阅读您HTML规范时发现对缩进的规则与示例不一致，缩进规则规定用“2个空格”作为一个缩进层级，但示例中是用的4个空格，不知是我理解有偏差，还是文档确需修改。
> 
> 如图： ![image](https://private-user-images.githubusercontent.com/5309179/351597108-d43cfbf6-285e-4344-9b46-0ce40d88ed80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzMyNzgsIm5iZiI6MTcyMTg3Mjk3OCwicGF0aCI6Ii81MzA5MTc5LzM1MTU5NzEwOC1kNDNjZmJmNi0yODVlLTQzNDQtOWI0Ni0wY2U0MGQ4OGVkODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMDIwMjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY2OWQ0MzkyMTkwODc2ZmEwNjUyNzk5ZWVkZDllYWQxZWQxYjhkOWVjZDNjOWZiYTY0ODY3NjdlMjVhODk5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3QjOarVz0CsJTxmjHV8OUICT6iFQ1BwU6lG96B1S1SM)

感谢反馈，已修改。
